### ISSUE TITLE
Todos - PT - Criação de Plano de Trabalho - Soma dos percentuais aumentando 1% 1%

### ISSUE THREAD

**Issue by rechInGov** [gestaogovbr/petrvs-pgd#119]

**Comment by guibitar** [comment]
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/116304761/0081d24e-1f66-47d4-8f7a-743cd606a913)

**Comment by rofarias** [comment]
Bug foi corrigido. 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/0f6453ba-7be9-40be-9e27-c532d5f43a06)
