### ISSUE TITLE
Participante e chefe -- Avaliação de PT. Múltiplos recursos. Permitir só um.

### ISSUE THREAD

**Issue by rechInGov** [gestaogovbr/petrvs-pgd#153]

**Comment by rofarias** [comment]
Sistema deve respeitar a estrutura da IN.
1 Só permitir a avaliação do PT 20 dias após o registro. Caso não ocorra, registrar que plano não foi avaliado (diferente de nota). Se possível bloquear gestão da chefia no sistema até avaliação dos registros pendentes.
2  Só permitir recurso do participante até dez dias da notificação da avaliação pela chefia. Caso não ocorra recurso, o plano é dado como concluído.
3 Só deve ser permitido ao participante **fazer um recurso** (hoje permite vários) e ele deve ser realizado no prazo de dez dias (ver 2.2). Bloquear múltiplos recursos. Somente um.
4 O chefe tem 10 dias para dizer se acata ou não as justificativas.




![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/bdaa58ab-725f-4d95-b8cb-53d760b06bd2)

**Comment by ktno08** [comment]
@LucVieir @rofarias 

Seguem alguns questionamentos sobre o card, para elaboração de requisitos adicionais:

1) Como deverá ser feita a contagem de prazos para os servidores que estiverem **afastados**?
2) Estabelecendo-se a regra para limitar a data de registro de execução pelo participante, como o sistema deve se comportar? Deve travar indeterminadamente sua inclusão? Deve permitir reabertura? Quais perfis podem executar a reabertura?
3) Como ficará a situação dos servidores que possuem planos de trabalho retroativos que ainda não possuem registros de execução e que não foram avaliados? 


Observação1: Em que pese a pendência dos outros requisitos relacionados aos prazos, o **módulo de notificações** poderá ser desde já tratado pela equipe
Observação2: O Card foi construído com o modelo de Bug, mas se trata de Story. Se possível, incluir as demais informações do modelo de User Story.

**Comment by geisimarrech87** [comment]
No Item 1, onde está escrito "inseriu seu registro de execução", o correto seria "concluiu"?

**Comment by rofarias** [comment]
Avançamos hoje bastante, mas ainda falta a questão do recurso.

**Comment by rofarias** [comment]
@ktno08 , abrimos o registro #461 para lidar com os pontos que você levantou. Deixaremos aqui somente a questão de múltiplos recursos. A questão do prazo foi excluída daqui. 

[#461](https://github.com/gestaogovbr/petrvs-pgd/issues/461)

**Comment by rofarias** [comment]
@ktno08 
1. Como deverá ser feita a contagem de prazos para os servidores que estiverem afastados?
A questão dos prazos deixou de ser relevante, em resultado da sugestão proposta de não ter trava temporal. 

2. Estabelecendo-se a regra para limitar a data de registro de execução pelo participante, como o sistema deve se comportar? Deve travar indeterminadamente sua inclusão? Deve permitir reabertura? Quais perfis podem executar a reabertura?
Mesma resposta da pergunta 1. 

4. Como ficará a situação dos servidores que possuem planos de trabalho retroativos que ainda não possuem registros de execução e que não foram avaliados?
Mesma resposta da pergunta 1.

**Comment by rofarias** [comment]
reeditamos

**Comment by ktno08** [comment]
**Teste - permissão de único recurso**

**Avaliação de chefe substituto da unidade**
Inadequado
- Permitiu 1 recurso - ok
Não executado
- Permitiu 1 recurso - ok
Adequado
- Permitiu 1 recurso - **erro.** 

**Avaliação de delegado da unidade**
Adequado
- Permitiu 1 recurso - **erro.**
Não executado
- Permitiu 1 recurso

**Avaliação de participante da unidade**
Não executado
- Permitiu 1 recurso - ok
Alto desempenho 
- **Não** permitiu recurso - ok
Excepcional
- Permitiu 1 recurso - **erro**
Adequado
- Permitiu 1 recurso - **erro.**


![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/def5d072-c7a0-44fb-8fee-159929cc54b0)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/7314c1a4-e503-4180-b134-b3331fe2ad5f)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/26a5d8f3-fd7f-443b-abbe-4952252e33ee)



**Resultado:**

A trava de permitir apenas um único recurso funciona, mas o sistema não está aderente aos casos que requerem recurso. Subtende-se que somente avaliações consideradas **inadequadas** ou **não executadas** que podem ser recorridas. Pela amostra do teste, somente aqueles considerados  como "alto desempenho" que não permitiram recurso. (Ref. card #411) (Ref. IN24/23, art. 21, § 4º )

Também cabem as seguintes observações:

1) sistema permite que mesmo após recurso, a chefia da unidade cancele a avaliação pós-recurso e faça uma nova, pior a anterior que pode prejudicar o participante, já que este não poderá mais entrar com novo recurso;
2) no formato atual, permite que o servidor receba uma avaliação pós-recurso pior que anterior (de inadequada para não executada);

Submeto:

À **área negocial** para conhecimento do resultado obtido e, se de acordo, estabelecer a seguinte regra no sistema:

- O sistema deve permitir que somente as avaliações "INADEQUADAS" e "NÃO EXECUTADAS" tenham recurso;

e

- deliberar sobre os itens 1 e 2

*Obs.: se de acordo, abrir novo card.

**Comment by LucVieir** [comment]
@ktno08, @rechInGov 

De acordo com a regra "O sistema deve permitir que somente as avaliações "INADEQUADAS" e "NÃO EXECUTADAS" tenham recurso".

Em relação ao item "1": após recurso, a chefia da unidade de execução não pode cancelar a avaliação incialmente feita. 

Em relação ao item "2": após o recurso, o sistema somente deve permitir que a chefia da unidade reavalie  para uma nota igual ou melhor que a inicialmente atribuída.

**Comment by LucVieir** [comment]
Encerrando esse ticket devido à abertura do ticket #510
