### ISSUE TITLE
API - Envio dos dados do Petrvs (produção) para API

### ISSUE THREAD

**Issue by rechInGov** [gestaogovbr/petrvs-pgd#173]
**Demandante:** [CGPGD ]

**Tipo de demanda:** [Funcionalidade]

**Persona:** [Desenvolvedor]

**O quê** [Realizar envio de dados do Petrvs em produção para a API em produção ]

**Para quê** [Viabilizar testes da API em produção]

**Definition of Ready** [ ]

**Definition of Done** [Dados do Petrvs em produção recebidos pela API do PGD em produção com sucesso ]

**Estimativa** [Preenchida nos campos do Card]

**Risco** [ ]

**Dependências** [Desenvolvimento da Integração Petrvs-PGD Ticket # ]

**Subtarefas**

**De que forma se conecta aos objetivos estratégicos?** [ ]

- [ ] - [x] sub tarefa 1 

- [x] sub tarefa 2

**Comment by rofarias** [comment]
Tiramos a urgência em decorrência do provável adiamento do prazo da IN.
