### ISSUE TITLE
Participante - Tela de Consolidações - Botão de informações de avaliação e mudança do Badge

### ISSUE THREAD

**Issue by brunoferreiraa1987** [gestaogovbr/petrvs-pgd#239]

**Comment by guibitar** [comment]
Versão Homologação 2.0.12. Duas reclamações de usuários no processo de avaliação.

Informação do resultado da avaliação escondido em uma tela poluída;
Não é possível ver a justificativa da chefia antes de clicar para o recurso.



![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/116304761/33ecc41b-54e2-4ba8-b544-f9d25468c854)



![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/116304761/fbb7c9e3-1b30-4b03-979e-0bd5b370d17b)
