### ISSUE TITLE
[Melhoria] [Plano de Trabalho] 

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#246]
**Quem reportou?** Keilla (Teste - Coges)

**Versão** 2.0.12

**Componente:** Descrição do plano de trabalho

**Qual plataforma?** dsv

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [ ]  perda de função grande
- [ ]  perda de função pequena,
- [x]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade:** baixa

**Descritivo**
Ao incluir um plano de trabalho, o campo "descrição" fica extremamente pequeno.
O campo descrição também é alterado seu tamanho conforme a quantidade de caracteres inseridos no título das entregas. 
Se uma quantidade de caracteres 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/b8f77211-b63d-4081-9e18-00e953d96056)

**Comment by ktno08** [comment]
Testado - segue para homologação. 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/ae61a14f-bfd0-4cf5-9a25-edd8edb86ce1)

**Comment by rofarias** [comment]
Homologado. Luciana, Thaís e Rogério
