### ISSUE TITLE
[Bug] [Plano de Trabalho] [Assinatura]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#249]
**Descrição**

Na assinatura do Plano de Trabalho proposto por chefe da unidade executora, não foi permitada assinatura de Chefe de Unidade Executora Superior Substituto+ (nível Coordenação-Geral), MAS o status do PT é de "aprovado"
Teste realizado por chefe da unidade executora (nível coordenação)

**Quem reportou?** 
Keilla (Teste-Coges)

**Versão**

**Componente**

**Qual plataforma?**
hmg

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [ ]  perda de função grande
- [x ]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

Prioridade

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/eb77d0dd-586a-4d75-ab2c-3952f60b3b28)

**Comment by rofarias** [comment]
Homologado. 16/04. Rogério e Luciana
