### ISSUE TITLE
[Bug] [Plano de Trabalho] [Inserir/Incluir]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#250]
**Descrição**
O sistema apresentou erro quando Chefe Substituto da Unidade Superior+ tentou incluir Plano de Trabalho para Chefe da Unidade Inferior.

**Quem reportou?**
Keilla (Testes-Coges)

**Versão**

**Componente**

**Qual plataforma?**
hmg

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [ ]  perda de função grande
- [x ]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade**

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/7b0f14db-f951-468f-b5f2-a3468feb6a81)

**Comment by rofarias** [comment]
Homologado em 16/04 com Luciana e Rogério.
