### ISSUE TITLE
[Bug] [Plano de Trabalho] [Assinatura]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#251]
**Descrição**
Plano de Trabalho proposto por Chefe da Unidade para ele mesmo, automatimaneto entra em execução após ser assinado. Mas não é permitido que o chefe da unidade superior assine o PT. 

**Quem reportou?**
Keilla (Testes-Coges)

**Versão**

**Componente**

**Qual plataforma?**
hmg 

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [ ]  perda de função grande
- [x ]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade**

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/287178ad-4f12-49d9-9a48-441935fb485b)

**Comment by rofarias** [comment]
Conferir Ticket #83 (https://github.com/gestaogovbr/petrvs-pgd/issues/83)

Conferir Ticket #201 (https://github.com/gestaogovbr/petrvs-pgd/issues/201)

**Comment by rofarias** [comment]
Homologado. 16/04.
