### ISSUE TITLE
[Bug] [Plano de Entregas] [Inserção de entregas]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#252]
**Descrição**

Ao incluir Plano de Entrega na Unidade, sistema não permite incluir entregas. É preciso gravar primeiro o PE para depois na tela Planejamento -> Plano de Entregas inserir as entregas que irão compor o PE.

**Quem reportou?**
Keilla (Testes-Coges)

**Versão**

**Componente**

**Qual plataforma?**
hmg

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [x ]  perda de função grande
- [ ] perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade** Alta

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/c7ce5c51-aed4-4206-8b4b-ddd7387ac483)

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/0cef3c86-6f48-449c-977b-bf1b1a797bc0)

**Comment by rofarias** [comment]
Homologado. Rogério e Luciana. 16/04.
