### ISSUE TITLE
[Funcionalidade] [Alterar unidade]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#253]
**Descrição**

F5/Atualizar página do sistema, ao realizar alteração de unidade, a página retorna para unidade anterior, em vez da nova unidade selecionada.

**Quem reportou?**
Keilla (Testes-Coges)

**Versão**

**Componente**

**Qual plataforma?**
hmg

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [ ] perda de função grande
- [ ]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade** Baixa

**Comment by rofarias** [comment]
Homologado 16/04. Luciana e Rogério.
