### ISSUE TITLE
[Bug] [Plano de Entregas] [Mensagem de erro]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#255]
**Descrição**

Agente delegado, com nível de acesso de administrador negocial, ao propor Plano de Entregas para unidade hierarquicamente subordinada incorre em erro na tela de entregas.
[Erro ao carregar dados: TypeError: Cannot read properties of undefined (reading.'path')

**Quem reportou?**
Keilla (Testes-Coges)

**Versão**

**Componente**

**Qual plataforma?**
hmg

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [x]  perda de função grande
- [ ]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade** Alta

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/7fbb6374-1eea-4522-bc2a-fb8ae3bf0cc6)

**Comment by rofarias** [comment]
Homologado por Luciana e Rogério. 16/04
