### ISSUE TITLE
Chefia - Execução de Plano de Entregas - 2.13 Produção - Comentários. Não é possível editar e visualização está ruim (ocupa espaço limitado).

### ISSUE THREAD

**Issue by rofarias** [gestaogovbr/petrvs-pgd#290]
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/199d8d66-9d85-48a7-a3f2-896adf43856c)

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/2bcc38db-974c-42ce-a15e-bbb7a3ec516f)

**Comment by rofarias** [comment]
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/b692c0cc-8192-4447-a75f-9f23cda44d21)

**Comment by juhelriguel** [comment]
Testar
