### ISSUE TITLE
Produção - 2.13 - Aprovação e avaliação de PTs pelas chefias imediatas quando unidade de execução é definida em nível superior

### ISSUE THREAD

**Issue by rofarias** [gestaogovbr/petrvs-pgd#293]
Quem reportou? Rogério de Souza Farias, Carol (Central), Simone (Seges)
Versão 2.13
Componente: Planejamento, Execução e avaliação
Qual plataforma? Produção 
Impacto: **Crítico**

Esse grave problema já havia sido detectado em fevereiro, causado quando uma unidade de execução com plano de entregas é definida em uma UORG acima (exemplo, DINOV), tendo os Planos de Trabalho de unidades UORGs inferiores (exemplo, (CGPGD) que se vincular a esse plano de entregas definido na unidade superior.

Problema: somente as chefias da unidade superior conseguem fazer a gestão dos PTs das unidades inferiores.

Gambiarra atual: colocar as chefias imediatas dos níveis inferiores como substitutas da unidade na qual o plano de entregas está ancorado. 

Regra correta, após correção: em casos em que um plano de trabalho esteja ligado a um plano de entregas de uma unidade superior, tanto as chefias das unidades superiores como a chefia imediata do participante do plano de entregas pode atuar em termos de proposta, aprovação e avaliação.

**Comment by ktno08** [comment]
Turma, conforme conversamos na daily negocial de hoje, segue análise relacionada a aprovação e avaliação de Planos de Trabalho pelas chefias imediatas quando unidade de execução é definida em nível inferior e Plano de Entrega é definido na unidade superior.

[Análise 2 - Plano de Entrega de Unidade Superior.docx](https://github.com/gestaogovbr/petrvs-pgd/files/15119758/Analise.2.-.Plano.de.Entrega.de.Unidade.Superior.docx)

@rofarias e @luciana (não consigo marcar a Lu!)

**Comment by LucVieir** [comment]
@ktno08, @geisimarrech87 e @guibitar, nosso encaminhamento negocial foi incluído no documento postado acima pela Keila.

**Comment by ktno08** [comment]
Encaminhamentos da área negocial


- [x] 1. **O sistema deve permitir a inclusão de Planos de Trabalho na unidade de lotação do participante com contribuições para entregas de unidades de execução de todos os níveis hierarquicamente superiores e inferiores (mobilidade vertical)**   
Obs1.: Esse ponto refere-se à tela “Inclusão de Plano de trabalho”. Na adição de contribuições em plano de trabalho criado na unidade de lotação do participante, usa-se no campo "origem", a opção de “outra unidade” (e devem aparecer no menu "selecione o plano de entrega" todos os planos de entrega vigentes das unidades organizacionais hierarquicamente superiores e inferiores).  
Obs2.: No caso de o participante incluir o Plano de Trabalho na unidade de execução superior ou inferior, diferente de sua lotação, aplica-se a regra do time volante, ou seja, requer-se a assinatura do chefe imediato e do chefe da unidade de execução na qual o plano foi incluído.   @geisimarrech87 
 
- [ ] _2. O sistema deve permitir a assinatura e avaliação pelos Chefes da unidade de execução e seus substitutos de Plano de Trabalho de participante lotado em qualquer nível de unidade hierarquicamente igual ou inferior (Card futuro | Documento em construção);_  

- [ ] 3. Relacionados aos times volantes: Manter a dinâmica encontrada nos resultados 2 e 3 (ou seja, requer-se a assinatura do chefe imediato e do chefe da unidade de execução na qual o plano foi incluído)

**Comment by ktno08** [comment]
Teste - Mobilidade Vertical (Plano de Trabalho)

**1)** Elaboração de Planos de Trabalho em nível de Coordenação-Geral, selecionando-se: 
a)unidade do agente público como a própria Coordenação-Geral 
b) origem do plano de trabalho de “outra unidade” 
c) seleção do Plano de Entregas da Diretoria 

**_Novo resultado:_**
Chefe para delegado - ok (duas assinaturas)
Chefe para Chefe substituto - ok  (duas assinaturas)
Chefe para participante - ok (duas assinaturas)

**2)** Elaboração de Planos de Trabalho em nível de Coordenação-Geral, selecionando-se (time volante): 
a) Unidade do agente público como a Diretoria 
b) Origem do plano de trabalho de “outra unidade” 
c) Seleção do Plano de Entregas da Diretoria 

**Novo Resultado:**
Chefe para delegado - ok 
Chefe para Chefe substituto - ok
Chefe para Participante - ok 

**3)** Elaboração de Planos de Trabalho em nível de Coordenação/Divisão, selecionando-se 
a) unidade do agente público como a própria Coordenação 
b) origem do plano de trabalho de “outra unidade” 
c) seleção do Plano de Entregas da Diretoria 

**Novo Resultado:**
Chefe para participante - ok
Chefe para chefe substituto - ok 
Chefe para delegado - ok 

**4)** Elaboração de Planos de Trabalho em nível de Coordenação/Divisão, selecionando-se (time volante): 
a) Unidade do agente público como a Diretoria 
b) Origem do plano de trabalho de “propria unidade” 
c) Seleção do Plano de Entregas da Diretoria 

**Novo Resultado:**
Chefe para participante - ok 
***Chefe para chefe substituto - ok
Chefe para delegado - ok 

**TESTE 2**
Requer-se a assinatura do chefe imediato e do chefe da unidade de execução na qual o plano foi incluído.
Requisito atendido

**TESTE 3**
No menu "selecione o plano de entrega" todos os planos de entrega vigentes das unidades organizacionais hierarquicamente superiores e inferiores)
Requisito atendido. É preciso utilizar o campo de pesquisa para selecionar os planos de entregas as unidades superiores e inferiores, mas é possível selecionar e propor planos de trabalho. 

**TESTE 4**
Avaliação
Item 1 e 3 - O sistema permite a avaliação pelos Chefes da unidade de lotação e seus substitutos de registros de execução de participante.
Item 1, 2, 3 e 4 -  O sistema permite a avaliação pelos Chefes da unidade de execução e seus substitutos de registros de execução de participante.

**Comment by rofarias** [comment]
Homologado Thaís e Rogério.
