### ISSUE TITLE
[Avaliação de Registro de Execução de chefia] [Bug]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#303]
**Descrição**

Chefe da unidade executora superior não consegue realizar avaliação de chefe da unidade inferior

**Quem reportou?**
Keilla (Testes-Coges)

**Versão**
2.0.13

**Componente**
Registro de Execução - Avaliação

**Qual plataforma?**
Produção

**Impacto**

- [ ]  Bloqueio,
- [x]  crítico,
- [ ]  perda de função grande
- [ ]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade** Alta

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/97aa4275-84a5-4c8e-a12f-fa3948c6afdd)

**Comment by guibitar** [comment]
Ainda ocorre o erro

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/116304761/148a2913-6b9b-4574-9f80-706b6fbf29c8)

**Comment by ktno08** [comment]
Resultado dos testes

1) Proposto planos de trabalho na unidade nível Coordenação-Geral para os perfis Chefe da Unidade e substituto para avaliação da chefia da unidade hierarquicamente superior - nível Diretoria.

Testes de assinatura: 
* sistema permitiu que o plano do chede da unidade fosse assinado pelo chefe da unidade hierarquicamente superior
* sistema permitiu que o plano do chefe da unidade substituto fosse assinado pelo chefe da unidade e pelo chefe da unidade hierarquicamente superior

Testes de avaliação
* sistema permitiu que o plano do chefe da unidade (CG) fosse avaliado pelo chefe da unidade hierarquicamente superior (Diretoria)
* sistema permitiu que o plano do chefe da unidade substituto (CG) fosse avaliado pelo chefe da sua própria unidade
* sistema permitiu que o plano do chefe da unidade substituto (CG) fosse avaliado pelo chefe da unidade hierarquicamente superior (Diretoria)

**Comment by LucVieir** [comment]
Homologado. Testado por Thaís, Luciana e Nathalia.
