### ISSUE TITLE
Encerramento automático da fase de registro do PT

### ISSUE THREAD

**Issue by rofarias** [gestaogovbr/petrvs-pgd#314]
**Descrição

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/cc02ac4b-7a5d-44ef-9235-cb83bf8ce13b)

**Quem reportou?**

**Versão**

**Componente**

**Qual plataforma?**

**Impacto**

- [ ] Bloqueio, 
- [ ] crítico, 
- [ ] perda de função grande
- [ ] perda de função pequena, 
- [ ] possível melhoria (avaliar criação de novo card)
- [ ] nova funcionalidade (avaliar criação de novo card)

**Prioridade**

**Comment by juhelriguel** [comment]
Repetido.
