### ISSUE TITLE
Configuração do Ambiente Treina

### ISSUE THREAD

**Issue by geisimarrech87** [gestaogovbr/petrvs-pgd#330]
**Produto:** [PGD PETRVS]

**Demandantes:** [ CGPGD, Administração Pública Federal*]

**Tipo de demanda:** [Configuração]

**O quê** [Trata-se da criação de 148 ambientes de treinamento/tenants para serem disponibilizados para a Administração Pública Federal]

**Para quê** [Os ambientes servem como base de treinamento dos futuros usuários do sistema e etapa da implementação e expansão do PGD PETRVS em toda APF. O MGI poderá ponderar possíveis falhas do sistema, bugs, qualidade do produto, segurança da operação e obter feedback de possíveis melhorias e desempenho do sistema]

**Definition of Done** [Ambientes estáveis e disponíveis para testes, análise do funcionamento do sistema e qualidade do produto]

**Dependências:** DTI (criação dos DNS), #275 

**Etapas/Subtarefas**

- [x] Melhorias da infraestrutura @MarcoCoelhoFirstMGI 
- [x] Seeder para Tenants @geisimarrech87 

**Celebrando nossas conquistas!

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/54d78baf-c9fa-4c89-9cd6-7a16a88ec46e)

!**

**Comment by geisimarrech87** [comment]
Demandante: CGPGD

Tipo de demanda: Configuração

Persona: [ ]

O quê: Criação de 148 tenants

Para quê: Treinamento das instituições

Dependências: DTI

**Comment by geisimarrech87** [comment]
Relatório dia 24/04: Aguardando propagação dos ajustes de SSL. Última pendência para finalizar.

**Comment by rofarias** [comment]
Homologado. Luciana e Rogério
