### ISSUE TITLE
[Bug][Histórico de Execução][Planos de entregas]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#335]
**Descrição** 
Ao acessar o menu Execução -> Planos de Entregas e alterar qualquer item editável das entregas cadastradas, tais como Etiquetas, Progresso/Checklist e Comentários, há alteração no Histórico de Execução. 
O correto é que apenas tenha alteração quando modificado o campo "Progresso/Checklist".

**Quem reportou?** Grupo Multiplicadores da Seges

Versão: 2.0.13

**Componente** Histórico de Execução de Planos de Entregas

**Qual plataforma?** hmg

**Impacto** 

- [ ]  Bloqueio,
- [ ]  crítico,
- [ ]  perda de função grande
- [ x]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade** Baixa

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/f939a18b-473f-4797-96d1-652ac2998cd3)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/bfa8404f-26b3-4067-8b5b-e1801a86b3f3)

**Comment by geisimarrech87** [comment]
Quanto alterar a meta, não precisa registrar o histórico de execução? @ktno08

**Comment by rofarias** [comment]
Comentário Luciana e Rogério. Primeiramente, esse bug não é estrutural. Não deveria nem ter entrado na sprint, por não ter prioridade. Segundo, o bug continua, como pode ser visto pelo vídeo. A qualquer operação de adição ou retirada de etiquetas, ele cria novo registro de execução da entrega, mesmo sem qualquer outras alteração.
Resolução: Voltar para o Backlog. 

https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/f4871dc3-6db0-48c5-8adc-4149cdb4cfd0

**Comment by geisimarrech87** [comment]
@rofarias pode fazer o teste novamente.

**Comment by rofarias** [comment]
Corrigido. Homologado por Luciana e Rogério.
