### ISSUE TITLE
[Bug][Informações do Registro de Execução]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#341]
**Descrição**
Ao acessar no menu o Registro de Execução e preencher o campo Progresso/Etiquetas/Checklist com percentual de progresso, ocorrem dois erros:
1º) Ao inserir um percentual de 100% e clicar em editar o percentual novamente, este passa para a ser multiplicado por 100. Se inserir qualquer outro número, o mesmo erro não ocorre.
2º) Ao inserir qualquer percentual e verificar o campo "Informações", o percentual passa a ser multiplicado por 100.

**Quem reportou?**
Grupo Multiplicadores Seges

**Versão**
2.0.13

**Componente**

**Qual plataforma?**
Dsv

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [ ]  perda de função grande
- [x]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade** baixa

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/9482ca9e-af35-48d5-9284-96dfb47043eb)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/73c44939-edaf-4644-b07c-bb0c00a7578c)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/a70c9228-f980-44e8-955f-248cd978c8fe)

**Comment by rofarias** [comment]
Não homologado. Rogério e Luciana. Problemas 1 e 2 foram sanados, mas há outro.

Ao criar um registro e alterar de 100% para outro valor, o sistema não permite salvar. Somente quando se conclui e o usuário retorna para editar a barra do "Progresso Etiquetas/Checklist" que se permite alterar de 100 para outro valor.
Mesmo assim, não é prioridade. Voltar para Backlog.

**Comment by rofarias** [comment]
https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/0e40ea17-31a2-45bb-9385-4e993385f683
