### ISSUE TITLE
BUG - erro ao atualizar cadastro do usuário com e-mail já vinculado.

### ISSUE THREAD

**Issue by ddobgestao** [gestaogovbr/petrvs-pgd#353]
Erro ao atualizar os dados cadastrais de um usuário quando o e-mail vindo do SIAPE tem uma e-mail já vinculado a outro usuário.

A solução será dar preferencia do e-mail para o SIAPE deixando o e-mail do usuário antigo com e-mail padrão.

**Comment by rofarias** [comment]
Não compreendemos o problema e tampouco a solução.
