### ISSUE TITLE
Ajustes no Seeder

### ISSUE THREAD

**Issue by LucVieir** [gestaogovbr/petrvs-pgd#411]
**Demandante:** [CGPGD ]
 
**Tipo de demanda:** [Correção]
 
**Persona:** [Todos os perfis]
 
**O quê** [Configurar o seeder da seguinte forma:
- Tipos de modalidades: devem aparecer apenas os cinco seguintes tipos de modalidades, na seguinte ordem:
 1) Presencial 
2) Teletrabalho parcial 
3) Teletrabalho integral
4) Teletrabalho com residência no exterior (hipóteses de substituição da Lei 8.112/90, inciso VIII do art. 12 do Decreto 11.072/2022)
5) Teletrabalho com residência no exterior (autorização discricionária, §7º do art. 12 Decreto 11.072/2022)
 - Tipos de avaliação: deve aparecer apenas duas opções de tipos de avaliação, uma para plano de trabalho e uma para plano de entrega, ambas contendo cinco níveis, com as seguintes notas, descrições e requisitos de justificativa:
1) Execução de plano de trabalho: 
I - excepcional: plano de trabalho executado muito acima do esperado
II - alto desempenho: plano de trabalho executado acima do esperado
III - adequado: plano de trabalho executado dentro do esperado
IV - inadequado: plano de trabalho executado abaixo do esperado ou parcialmente executado
V - não executado: plano de trabalho integralmente não executado
Requer justificativa: I, IV e V.

2) Execução de plano de entrega:
I - excepcional: plano de entregas executado com desempenho muito acima do esperado;
II - alto desempenho: plano de entregas executado com desempenho acima do esperado;
III - adequado: plano de entregas executado dentro do esperado;
IV - inadequado: plano de entregas executado abaixo do esperado; e
V - plano de entregas não executado
Requer justificativa: nenhum.
- Tipos de Justificativa: não apresentar nenhum tipo de justificativa “pré-fabricada”
- Pergunta motivacional: não apresentar nenhuma pergunta motivacional 
- Ícone/Cor: utilizar como deafult a seguinte combinação de ícones/cores para cada nível de avaliação:
I - excepcional: emoji feliz/azul
II - alto desempenho: emoji feliz/azul claro
III - adequado: emoji feliz/verde
IV - inadequado: emoji triste/laranja
V - não executado: emoji triste/vermelho
]
 

- Tela de chefia. Mudar capacidade para aparecer Cadeia de valor.

**Para quê** [Assegurar que itens mandatórios do regramento sejam exibidos corretamente e como default do sistema. Mitigar o risco de que aspectos mandatórios do PGD que não deveriam ser configuráveis sejam configurados de maneira errada pelos Administradores Negociais]
 
**Definition of Ready** [ ]
 
 
**Definition of Done** [As configurações descritas em “o quê” aparecem no sistema como default e administradores negociais não podem criar outros tipos de modalidade/avaliação. Justificativas pré-fabricadas não podem ser cadastradas por administradores negociais. Perguntas motivacionais não aparecem como default.]
 
 
**Estimativa** [Preenchida nos campos do Card]
 
 
**Risco** [ ]
 
 
**Dependências** [ ]
 
 
**Subtarefas**
 
 
**De que forma se conecta aos objetivos estratégicos?** [ ]
 
 
- [ ] - [x] sub tarefa 1
 
- [ ] sub tarefa 2

**Comment by geisimarrech87** [comment]
Os ajustes nesse seeder e no seeder de capacidades para bloquear o perfil de Administrador negocial de criar esses registros, não corrige os planos que já usaram dados indevidos.  
Nesse caso sugiro abrir outro card para correção desses registros e qual estratégia usar para corrigir.

**Comment by LucVieir** [comment]
@geisimarrech87 e @guibitar, é importante corrigir os planos que já usaram dados indevidos? 
Tendo a achar que não, pois apenas a Seges está usando em produção e, conforme, explicado por vocês, quando entrar em vigor no MGI todo (novo regramento), o que existe hoje na SEGES será "zerado". Me parece que o importante é que quando for lançado para a APF (MGI incluído) esteja correto. O que vocês acham?

**Comment by LucVieir** [comment]
@geisimarrech87 e @guibitar, localizamos o ticket referente ao sombreamento que comentamos ontem que deve andar junto com esse ajuste no Seeder. É o ticket #358, que puxei para a raia de Backlog.

**Comment by rofarias** [comment]
Apresentado na reunião daily 7 de maio. Na tela da chefia, só aparece o "Planejamentos Institucionais". 


![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/d92abf6f-15df-4653-98f4-6b39a495ef66)

**Comment by geisimarrech87** [comment]
Quais as capacidades que o Adm Negocial pode ter em relação ao cadastro, edição e exclusão dos "Tipos" relacionados ao card?
@rofarias @LucVieir

**Comment by rofarias** [comment]
Sugestão de desligamentos:



![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/8a97d2e4-bfac-43bb-b3df-9c08ca229d64)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/eb919e7f-03d9-4052-a30d-1bb766624be7)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/39994645-60c7-405d-9e4b-b16ad39d06da)

**Comment by geisimarrech87** [comment]
@rofarias @LucVieir 
Tirei desse seeder o cadastro de:
Regramento padrão MGI;
Planejamento, eixos temáticos e cadeia de valor;

Concordam?

**Comment by rofarias** [comment]
@geisimarrech87 , não entendi sua pergunta. Podemos amanhã na daily ter uma visão da tela proposta?

**Comment by rofarias** [comment]
Não foi homologado. Vários problemas:

1) Iniciando pelas cores, que não seguiram a orientação acima:
Ícone/Cor: utilizar como deafult a seguinte combinação de ícones/cores para cada nível de avaliação:
I - excepcional: emoji feliz/azul
II - alto desempenho: emoji feliz/azul claro
III - adequado: emoji feliz/verde
IV - inadequado: emoji triste/laranja
V - não executado: emoji triste/vermelho

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/7dd0cfc4-2e75-4bb2-9a38-7e3ec141c2b5)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/554c3f0a-1e40-4d28-83eb-62c26176432d)

2) Tela de chefia. **Mudar capacidade para aparecer Cadeia de valor**. Lembrando que chefia pode visualizar Planejamento Institucional e Cadeia de Valor, mas não poderá modificá-lo.
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/7a52df86-f929-47b4-ae0c-a0d8ad2a0595)

**Comment by rofarias** [comment]
Continuam errados. Testei em regramento novo no Treina.

![Screenshot 2024-06-03 at 19 49 13](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/5c94f7a6-4efb-47e5-8645-9d8a8fe956f0)
![Screenshot 2024-06-03 at 19 45 32](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/463049e9-caf0-471d-b586-e58ddcf6c6d0)
