### ISSUE TITLE
[Bug] [Inclusão/alteração de perfil]

### ISSUE THREAD

**Issue by ktno08** [gestaogovbr/petrvs-pgd#472]
**Descrição**
O sistema incorre em erro ao editar uma atribuição de uma perfil de chefia

**Quem reportou?**
CGPGD

**Versão**
DSV 2.0.14 e HMG 2.0.14

**Componente**
Edição de agente público

**Qual plataforma?**
dsv e hmg 

**Impacto**

- [ ]  Bloqueio,
- [ ]  crítico,
- [X]  perda de função grande
- [ ]  perda de função pequena,
- [ ]  possível melhoria (avaliar criação de novo card)
- [ ]  nova funcionalidade (avaliar criação de novo card)

**Prioridade** Alta

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/4a8985a7-1a04-452b-8f0e-e7865bac5ebc)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/39c1b3e1-1425-4577-bfd4-58c82213449b)
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/b21a0e4d-0fbb-4cec-ba42-a251e92ba339)

**Comment by ktno08** [comment]
Testado. 
Alterado perfil de participante para chefe da unidade.
Alterado perfil de delegado para chefe da unidade.
Alterado perfil de participante para chefe da unidade e nível de acesso de administrador.
Alterado perfil de chefe da unidade para delegado.
Alterdo perfil de chefe da unidade para participante.

**Comment by LucVieir** [comment]
Testado por Thais. Homologado.
