### ISSUE TITLE
[Ocorrências][Afastamentos][Retirar o módulo de Ocorrências]

### ISSUE THREAD

**Issue by guibitar** [gestaogovbr/petrvs-pgd#485]
Produto: [ PGD PETRVS]

Demandante: [COGES]

Tipo de demanda: [Evolução]

O quê [ Definição de uso dos módulos de ocorrências e de afastamento]

Risco [Descrito no documento anexo ]

Para quê [ Definir como os módulos se comportam]

Dependências [ ]

Subtarefas

 - [x] Editar Capacidade nos ambientes(dsv, hmg, prd), retirar menu de Ocorrência de todos os perfis
 - [x] Retirar marcação das capacidades relacionadas no seeder 
 - [x] Editar Tela de registro de execução, retirar a divisória de Ocorrência dos registros e telas relacionadas

**Comment by rofarias** [comment]
Ainda aparece no prd no perfil de administrador negocial.
![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/6db6474a-d893-4f3c-b2e9-84d75d996046)

No homologação foi retirado das duas telas.

**Comment by rofarias** [comment]
Homologado.
