### ISSUE TITLE
Bug na avaliação de planos de entregas

### ISSUE THREAD

**Issue by rofarias** [gestaogovbr/petrvs-pgd#492]
**Descrição

 1.Acessei o sistema como chefe da DINOV:
 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/3ddd43fb-2ac3-427f-8233-fadfcd9f3dc4)

2. Busquei os planos de entregas da CGPGD que estavam concluídos e disponíveis para avaliação:
 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/f6867425-dd53-4ec9-90ce-cd0a1ee387f3)

 
3. Encontrei 11 planos de entregas (1 já avaliado e 10 concluídos, aguardando avaliação). Tentei avaliar os 10 que estavam disponíveis para avaliação e todos apresentaram erro.
 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/dcace35f-9e20-4ecb-8836-bc273904b58b)

 
a. o plano de entregas taxado em amarelo acima (PE #91 da CGPD), apresentou "erro ao carregar os dados" (conforme print abaixo). Observando melhor, vi que ele não está vinculado a nenhum "programa de gestão" (regramento institucional), o que não faz sentido, pois o sistema não deveria permitir ele passar por todas as etapas do ciclo (planejamento, execução) e dar problema somente na avaliação. É bug? É configuração? Não consegui descobrir.
 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/7677f7e3-0449-4196-b38a-620165f07d99)

 
b. Todos os outros 9 planos de entregas apresentaram o seguinte erro, que também não consegui identificar a causa: 
 

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/13226112/8335271f-192b-409d-8706-e1382167f9f9)

**Quem reportou?** THAÍS BARRAL

**Versão**14

**Componente** Avaliação do Plano de Entregas

**Qual plataforma?** HMG

**Impacto**

- [ ] Bloqueio, 
- [ ] crítico, 
- [X ] perda de função grande
- [ ] perda de função pequena, 
- [ ] possível melhoria (avaliar criação de novo card)
- [ ] nova funcionalidade (avaliar criação de novo card)

**Prioridade**

**Comment by ktno08** [comment]
Bug na avaliação da entrega permanece:

![Image](https://github.com/gestaogovbr/petrvs-pgd/assets/164068830/465bb9d2-d145-45bc-bc95-79cf1abdb22a)

**Comment by rofarias** [comment]
Homologado. Nathália, Luciana e Rogério
