### ISSUE TITLE
Cadastrar a mesma atribuição mais de uma vez ao participante

### ISSUE THREAD

**Issue by rofarias** [gestaogovbr/petrvs-pgd#548]
**Descrição
É possível cadastrar a mesma atribuição mais de uma vez ao participante. 

**Quem reportou?**
Fiocruz
**Versão**
2.15
**Componente**
Perfil

**Qual plataforma?**

treina

**Impacto**

- [ ] Bloqueio, 
- [ ] crítico, 
- [ ] perda de função grande
- [X] perda de função pequena, 
- [ ] possível melhoria (avaliar criação de novo card)
- [ ] nova funcionalidade (avaliar criação de novo card)

**Prioridade**

**Comment by juhelriguel** [comment]
Resolvido.
