### ISSUE TITLE
Gestor - Avaliação de Plano de Trabalho de Chefe de unidade

### ISSUE THREAD

**Issue by rechInGov** [gestaogovbr/petrvs-pgd#83]

**Comment by guibitar** [comment]
Necessário retestar essa situação para detalhamento do Ticket 

Verificar se a situação ocorre e em quais ambientes

**Comment by rofarias** [comment]
Testado no ambiente de homologação 2.012. Chefia da DIPROG concluiu registro de plano de trabalho, mas na tela da chefia da unidade superior (CGLEG) não abriu ícone de avaliação. Somente quando a chefia da unidade superior foi colocada como chefe substituta da unidade inferior que abriu a "estrela" de avaliação. Ticket muito semelhante ao #201

**Comment by ktno08** [comment]
Resultado reportado no card #201

**Comment by LucVieir** [comment]
Testado conforme #303 . Homologado.
